const MANAGER = 'project_manager';
const MEMBER = 'project_member';
// const OBSERVER = 'project_observer';

const EXPORT_DATA_ROLES = [MANAGER, MEMBER];
const WRITE_OBJECTS_ROLES = [MANAGER, MEMBER];
const WRITE_VIEWS_ROLES = [MANAGER, MEMBER];
const WRITE_COMMENTS_ROLES = [MANAGER, MEMBER];
const READ_TASKS_ROLES = [MANAGER, MEMBER];
const WRITE_PROJECT_ROLES = [MANAGER];
const WRITE_IMAGES_ROLES = [MANAGER];
const DELETE_IMAGES_ROLES = [MANAGER];
const MANAGE_USERS_ROLES = [MANAGER];
const WRITE_DEPLOYMENTS_ROLES = [MANAGER];
const WRITE_AUTOMATION_RULES_ROLES = [MANAGER];
const WRITE_CAMERA_REGISTRATION_ROLES = [MANAGER];
const WRITE_CAMERA_SERIAL_NUMBER_ROLES = [MANAGER];

export {
  READ_TASKS_ROLES,
  WRITE_COMMENTS_ROLES,
  DELETE_IMAGES_ROLES,
  EXPORT_DATA_ROLES,
  MANAGE_USERS_ROLES,
  WRITE_PROJECT_ROLES,
  WRITE_OBJECTS_ROLES,
  WRITE_VIEWS_ROLES,
  WRITE_IMAGES_ROLES,
  WRITE_DEPLOYMENTS_ROLES,
  WRITE_AUTOMATION_RULES_ROLES,
  WRITE_CAMERA_REGISTRATION_ROLES,
  WRITE_CAMERA_SERIAL_NUMBER_ROLES,
};
