FROM ubuntu:22.04

ENV HOME=/home/animl
WORKDIR $HOME
COPY ./ $HOME/

RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y curl git

RUN export NODEV='20.12.2' \
    && curl "https://nodejs.org/dist/v${NODEV}/node-v${NODEV}-linux-x64.tar.gz" | tar -xzv \
    && cp ./node-v${NODEV}-linux-x64/bin/node /usr/bin/ \
    && ./node-v${NODEV}-linux-x64/bin/npm install -g npm

RUN npm install

# Verify project successfully builds with type-checks
CMD npm run build && \
    # Verify tests pass
    npm test && \
    # Lint project
    npm run lint && \
    # Ensure that codegen is successful
    npm run codegen && \
    # Ensure that codegen output is committed
    sh -c \
        'if [ "$CHECK_CODEGEN" = "true" ]; then \
            if [ -n "$(git status --porcelain src/@types)" ]; then \
                echo "Uncommitted changes detected after running codegen"; \
                git status; \
                exit 1; \
            else \
                echo "No uncommitted changes detected"; \
            fi; \
        else \
            echo "CHECK_CODEGEN flag not set, skipping uncommitted changes check"; \
        fi'
