service: animl-graphql-api

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${env:STAGE}
  region: ${env:REGION}
  profile: ${env:AWS_PROFILE}
  # Only necessary for private endpoints
  # apiKeys:
  #   - name: lambdaApolloKey
  #     value: ${env:APOLLO_LAMBDA_KEY}

functions:
  graphql:
    handler: src/handler.server
    events:
    - http:
        path: /
        method: post
        cors: true
  playground:
    handler: src/handler.playground
    events:
    - http:
        path: /
        method: get
        cors: true