org: animl
app: animl
service: animl-api

plugins:
  # TODO: figure out serverless-offline-sqs
  # - serverless-offline-sqs
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${env:STAGE}
  region: ${env:REGION}
  profile: ${env:AWS_PROFILE}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sqs:*
      Resource:
        - Fn::GetAtt:
            - inferenceQueue
            - Arn
    - Effect: Allow
      Action:
        - ses:SendEmail
        - ses:SendRawEmail
      Resource: "*"
  # Only necessary for private endpoints
  # apiKeys:
  #   - name: lambdaApolloKey
  #     value: ${env:APOLLO_LAMBDA_KEY}

functions:
  graphql:
    handler: src/api/handler.server
    events:
    - http:
        path: /
        method: post
        cors: true
    timeout: 20
  playground:
    handler: src/api/handler.playground
    events:
    - http:
        path: /
        method: get
        cors: true
    timeout: 20
  inference:
    handler: src/ml/handler.inference
    reservedConcurrency: 10 # max number of lambdas to invoke at one time
    events:
      - eventBridge:
          schedule: rate(5 minutes)
      # - sqs:
      #     arn:
      #       Fn::GetAtt:
      #         - inferenceQueue
      #         - Arn
      #     batchSize: 1
    timeout: 120

resources:
  Resources:
    inferenceQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: inferenceQueue
        RedrivePolicy:
          deadLetterTargetArn:
            "Fn::GetAtt":
              - inferenceDeadLetterQueue
              - Arn
          maxReceiveCount: 5
    inferenceDeadLetterQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "inferenceDLQ"
        MessageRetentionPeriod: 1209600 # 14 days in seconds