org: animl
app: animl
service: animl-api

plugins:
  # TODO: figure out serverless-offline-sqs
  # - serverless-offline-sqs
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${env:STAGE}
  region: ${env:REGION}
  profile: ${env:AWS_PROFILE}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sqs:SendMessage
      Resource:
        - Fn::GetAtt:
            - animlAutomationQueue
            - Arn
    - Effect: Allow
      Action:
        - ses:SendEmail
        - ses:SendRawEmail
      Resource: "*"
  # Only necessary for private endpoints
  # apiKeys:
  #   - name: lambdaApolloKey
  #     value: ${env:APOLLO_LAMBDA_KEY}

functions:
  graphql:
    handler: src/api/handler.server
    events:
    - http:
        path: /
        method: post
        cors: true
    timeout: 20
  playground:
    handler: src/api/handler.playground
    events:
    - http:
        path: /
        method: get
        cors: true
    timeout: 20
  automation:
    handler: src/automation/handler.automation
    reservedConcurrency: 10 # max number of lambdas to invoke at one time
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - animlAutomationQueue
              - Arn
          batchSize: 1
    timeout: 20

resources:
  Resources:
    animlAutomationQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: animlAutomationQueue.fifo
        FifoQueue: true
        ContentBasedDeduplication: true